language: node_js

node_js:
  - "8"

env:
  - SET=android-1-2 SYS=browserstack
  - SET=android-4 SYS=browserstack
  - SET=chrome SYS=browserstack
  - SET=edge SYS=browserstack
  - SET=firefox SYS=browserstack
  - SET=internet-explorer SYS=browserstack
  - SET=ios-3-4 SYS=browserstack
  - SET=ios-5-plus SYS=browserstack
  - SET=opera SYS=browserstack
  - SET=safari SYS=browserstack
  - SET=windows-phone SYS=browserstack
  - SET=yandex SYS=browserstack

before_script:
  - ./node_modules/.bin/cbtr-browserstack-update
  - npm run instrument
  - npm run test-js
  - npm run test-server > ~/.bjs.test-server.log 2>&1 &

after_script:
  - npm run coverage

cache:
  directories:
    - "node_modules"

addons:
  hosts:
    - build.browsejs.org
